#' ---
#' title: 'Association btw testis PRS (gwas) and risk of relapse in CS I tumor patients under SURVEILLANCE'
#' author: Emilio Ugalde
#' Date: 2024-11-22
#' ---
#' 
#' **DESCRIPTION** \
#' This scripts include: \
#' - Cox Regression analyses for association of PRS as continuous and categorical using both un-adjusted and adjusted models for:
#'     + **age at diagnosis and 3 PCs**. \
#'     + **age at diagnosis, vascular invasion, and 3 PCs**. \
#' 
#' 
## ----setup, include=FALSE, echo=F---------------------------------------------
suppressMessages(library("survival"))
suppressMessages(library("broom"))


#' Working directory
## ----echo=T-------------------------------------------------------------------
args <- commandArgs(trailingOnly = TRUE)
wd <- args[1]
if(is.na(wd)==T) wd=""

#' ## INPUT
# load dataset generated by "Format_Px_data_*.R" scripts
load(paste0(wd, './Data/patient_data.Rdat'))

#' 
#' Set OUTPUT
## ----echo=T-------------------------------------------------------------------
dir_out <- paste0(wd, "results/Tables/")
date_a <- format(Sys.Date(), "%Y%m%d")

#' 
#' - Results on relapse stage I under surveillance: 
#' For each covariate
## -----------------------------------------------------------------------------
file1 = paste0("Table_Covariates_relapse_CI_surveillance.", date_a, ".txt" )
#' 
#' - Results on relapse stage I under surveillance: 
#' PRS (un-adjusted, and adjusted models)
## -----------------------------------------------------------------------------
file2 = paste0("Table_gwasPRS_relapse_CI_surveillance.", date_a, ".txt" )
file2a = paste0("Table_gwasPRS_relapse_CI_surveillance_agedx_3PC_Adj.", date_a, ".txt" ) 
file2b = paste0("Table_gwasPRS_relapse_CI_surveillance_agedx_vasc_3PC_Adj.", date_a, ".txt" ) 

#' ## Summary functions
## -----------------------------------------------------------------------------
# Rounding
RD=2

#' 
## ----include=F----------------------------------------------------------------
# output summary function
sum_cox_out <- function(model, name) {
  out <- as.data.frame(tidy(model, exp=T, conf.int = T)[, c("term","estimate", "conf.low", "conf.high","p.value")])
  out$estimate <- round(out$estimate, RD)
  out$CI <- paste0(round(out$conf.low, RD), " to ", round(out$conf.high, RD))
  out <- out[, c("term","estimate", "CI","p.value")]
  colnames(out) <- c("Model","HR","95%CI","p.value")
  out$Model <- c(name)
  out[1,]
}
# for binary PRS
sum_cox_out2 <- function(model, name) {
  out <- as.data.frame(tidy(model, exp=T, conf.int = T)[, c("term","estimate", "conf.low", "conf.high","p.value")])
  out$estimate <- round(out$estimate, RD)
  out$CI <- paste0(round(out$conf.low, RD), " to ", round(out$conf.high, RD))
  out <- out[, c("term","estimate", "CI","p.value")]
  colnames(out) <- c("Model","HR","95%CI","p.value")
  out <- out[1,]
  out$Model <- c(name)
  out
}
# for categorical PRS
# Assuming levels from first categorical variable (i.e. in this case, PRS tertiles)
sum_cox_out3 <- function(model, name) {
  out <- as.data.frame(tidy(model, exp=T, conf.int = T)[, c("term","estimate", "conf.low", "conf.high","p.value")])
  out$estimate <- round(out$estimate, RD)
  out$CI <- paste0(round(out$conf.low, RD), " to ", round(out$conf.high, RD))
  out <- out[, c("term","estimate", "CI","p.value")]
  colnames(out) <- c("Model","HR","95%CI","p.value")
  levels <- as.character(unlist(model$xlevels[[1]]))
  levels <- levels[2:length(levels)]
  out <- out[1:(length(levels)), ]
  out$Model <- paste0(name, " (",levels, ")")
  out
}

#' # Cox analysis: in stage I cases under surveillance
## ----echo=T-------------------------------------------------------------------

# Subset
data_s <- subset(clin, rmh=="CS I" & prim_beh=="Surveillance")

#' 
#' - Association of each covariate with relapse
## -----------------------------------------------------------------------------
cov_test <- c("agediag", "vasc_x", "tumortype", "PC1", "PC2", "PC3")
out_cov <- data.frame(covariate=cov_test, coef=rep(NA, length(cov_test)), coef.exp=rep(NA, length(cov_test)), coef.se=rep(NA, length(cov_test)),
                      z=rep(NA, length(cov_test)), P=rep(NA, length(cov_test)) )
for(C in cov_test){
    fm=formula(paste("Surv(timerec, recpro) ~", C, collapse = "") )
    res <- summary(coxph(fm, data=data_s))$coefficients
    out_cov[out_cov$covariate==C, ]$coef <- res[1,1]
    out_cov[out_cov$covariate==C, ]$coef.exp <- res[1,2]
    out_cov[out_cov$covariate==C, ]$coef.se <- res[1,3]
    out_cov[out_cov$covariate==C, ]$z <- res[1,4]
    out_cov[out_cov$covariate==C, ]$P <- res[1,5]
    rm(res)
}
out_cov$covariate <- c("Age diagnosis, yrs", "Vasc. infiltration (Yes vs. No)", "Hist (Sem vs. Non-sem)", "PC1", "PC2", "PC3")
# Save
write.table(out_cov, file=paste0(dir_out, file1), col.names=T, row.names = F, quote=F, sep="\t")

#' 
#' - Compile estimates per 1-SD 
## -----------------------------------------------------------------------------
# Overall
out_cox_1 <- sum_cox_out(coxph(Surv(timerec, recpro)  ~ PRS_gwas_SDcases, data=data_s), "Un-adjusted (1-SD)")
out_cox_1a <- sum_cox_out(coxph(Surv(timerec, recpro)  ~ PRS_gwas_SDcases + agediag + PC1 + PC2 + PC3, data=data_s), "Cov. adjusted (1-SD)")
out_cox_1b <- sum_cox_out(coxph(Surv(timerec, recpro)  ~ PRS_gwas_SDcases + agediag + vasc_x + PC1 + PC2 + PC3, data=data_s), "Cov. adjusted* (1-SD)")

# SEMINOMAS
out_cox_S1 <- sum_cox_out(coxph(Surv(timerec, recpro)  ~ PRS_gwas_SDcases, data=subset(data_s, tumortype=="Seminom")), "Un-adjusted (1-SD)" )
out_cox_S1a <- sum_cox_out(coxph(Surv(timerec, recpro)  ~ PRS_gwas_SDcases + agediag + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Seminom")), "Cov. adjusted (1-SD)" )
out_cox_S1b <- sum_cox_out(coxph(Surv(timerec, recpro)  ~ PRS_gwas_SDcases + agediag + vasc_x + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Seminom")), "Cov. adjusted* (1-SD)" )

# NON-SEMINOMAS
out_cox_NS1 <- sum_cox_out(coxph(Surv(timerec, recpro)  ~ PRS_gwas_SDcases, data=subset(data_s, tumortype=="Nonseminom")), "Un-adjusted (1-SD)" )
out_cox_NS1a <- sum_cox_out(coxph(Surv(timerec, recpro)  ~ PRS_gwas_SDcases + agediag + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Nonseminom")), "Cov. adjusted (1-SD)" )
out_cox_NS1b <- sum_cox_out(coxph(Surv(timerec, recpro)  ~ PRS_gwas_SDcases + agediag + vasc_x + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Nonseminom")), "Cov. adjusted* (1-SD)" )

#' 
#' - Compile estimates by mean distribution
## -----------------------------------------------------------------------------
# Overall
out_cox_2 <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_mean, data=data_s), "Un-adjusted (>=mean)")
out_cox_2a <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_mean + agediag + PC1 + PC2 + PC3, data=data_s), "Cov. adjusted (>=mean)")
out_cox_2b <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_mean + agediag + vasc_x + PC1 + PC2 + PC3, data=data_s), "Cov. adjusted* (>=mean)")

# SEMINOMAS
out_cox_S2 <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_mean, data=subset(data_s, tumortype=="Seminom")), "Un-adjusted (>=mean)" )
out_cox_S2a <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_mean + agediag + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Seminom")), "Cov. adjusted (>=mean)" )
out_cox_S2b <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_mean + agediag + vasc_x + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Seminom")), "Cov. adjusted* (>=mean)" )

# NON-SEMINOMAS
out_cox_NS2 <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_mean, data=subset(data_s, tumortype=="Nonseminom")), "Un-adjusted (>=mean)" )
out_cox_NS2a <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_mean + agediag + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Nonseminom")), "Cov. adjusted (>=mean)" )
out_cox_NS2b <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_mean + agediag + vasc_x + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Nonseminom")), "Cov. adjusted* (>=mean)" )

#' 
#' - Compile estimates by MEDIAN distribution
## -----------------------------------------------------------------------------
# Overall
out_cox_2m <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_median, data=data_s), "Un-adjusted (>=median)")
out_cox_2ma <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_median + agediag + PC1 + PC2 + PC3, data=data_s), "Cov. adjusted (>=median)")
out_cox_2mb <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_median + agediag + vasc_x + PC1 + PC2 + PC3, data=data_s), "Cov. adjusted* (>=median)")

# SEMINOMAS
out_cox_S2m <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_median, data=subset(data_s, tumortype=="Seminom")), "Un-adjusted (>=median)" )
out_cox_S2ma <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_median + agediag + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Seminom")), "Cov. adjusted (>=median)" )
out_cox_S2mb <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_median + agediag + vasc_x + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Seminom")), "Cov. adjusted* (>=median)" )

# NON-SEMINOMAS
out_cox_NSm2 <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_median, data=subset(data_s, tumortype=="Nonseminom")), "Un-adjusted (>=median)" )
out_cox_NSm2a <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_median + agediag + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Nonseminom")), "Cov. adjusted (>=median)" )
out_cox_NSm2b <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_median + agediag + vasc_x + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Nonseminom")), "Cov. adjusted* (>=median)" )

#' 
#' - Compile estimates by TERTILE distribution
## -----------------------------------------------------------------------------
# Overall
out_cox_03m <- sum_cox_out3(coxph(Surv(timerec, recpro)  ~ PRS_gwas_tert_c, data=data_s), "Un-adjusted")
out_cox_03ma <- sum_cox_out3(coxph(Surv(timerec, recpro)  ~ PRS_gwas_tert_c + agediag + PC1 + PC2 + PC3, data=data_s), "Cov. adjusted")
out_cox_03mb <- sum_cox_out3(coxph(Surv(timerec, recpro)  ~ PRS_gwas_tert_c + agediag + vasc_x + PC1 + PC2 + PC3, data=data_s), "Cov. adjusted*")

# SEMINOMAS
out_cox_S03m <- sum_cox_out3(coxph(Surv(timerec, recpro)  ~ PRS_gwas_tert_c, data=subset(data_s, tumortype=="Seminom")), "Un-adjusted" )
out_cox_S03ma <- sum_cox_out3(coxph(Surv(timerec, recpro)  ~ PRS_gwas_tert_c + agediag + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Seminom")), "Cov. adjusted" )
out_cox_S03mb <- sum_cox_out3(coxph(Surv(timerec, recpro)  ~ PRS_gwas_tert_c + agediag + vasc_x + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Seminom")), "Cov. adjusted*" )

# NON-SEMINOMAS
out_cox_NSm03 <- sum_cox_out3(coxph(Surv(timerec, recpro)  ~ PRS_gwas_tert_c, data=subset(data_s, tumortype=="Nonseminom")), "Un-adjusted" )
out_cox_NSm03a <- sum_cox_out3(coxph(Surv(timerec, recpro)  ~ PRS_gwas_tert_c + agediag + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Nonseminom")), "Cov. adjusted" )
out_cox_NSm03b <- sum_cox_out3(coxph(Surv(timerec, recpro)  ~ PRS_gwas_tert_c + agediag + vasc_x + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Nonseminom")), "Cov. adjusted*" )

#' 
#' - Compile estimates by high vs low tertile distribution
## -----------------------------------------------------------------------------
# Overall
out_cox_3 <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_th, data=data_s), "Un-adjusted (>1st tertile)")
out_cox_3a <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_th + agediag + PC1 + PC2 + PC3, data=data_s), "Cov. adjusted (>1st tertile)")
out_cox_3b <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_th + agediag + vasc_x + PC1 + PC2 + PC3, data=data_s), "Cov. adjusted* (>1st tertile)")

# SEMINOMAS
out_cox_S3 <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_th, data=subset(data_s, tumortype=="Seminom")), "Un-adjusted (>1st tertile)" )
out_cox_S3a <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_th + agediag + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Seminom")), "Cov. adjusted (>1st tertile)" )
out_cox_S3b <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_th + agediag + vasc_x + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Seminom")), "Cov. adjusted* (>1st tertile)" )

# NON-SEMINOMAS
out_cox_NS3 <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_th, data=subset(data_s, tumortype=="Nonseminom")), "Un-adjusted (>1st tertile)" )
out_cox_NS3a <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_th + agediag + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Nonseminom")), "Cov. adjusted (>1st tertile)" )
out_cox_NS3b <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_th + agediag + vasc_x + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Nonseminom")), "Cov. adjusted* (>1st tertile)" )

#' 
#' - Prepare table header (n, nevents)
## -----------------------------------------------------------------------------
ov=paste0("Overall", " (n=", length(data_s$recpro[is.na(data_s$recpro)==F]), ", ", as.numeric(table(data_s$recpro)[2])," events)")
se=paste0("Seminoma", " (n=", length(subset(data_s, tumortype=="Seminom")$recpro[is.na(subset(data_s, tumortype=="Seminom")$recpro)==F]), ", ", as.numeric(table(subset(data_s, tumortype=="Seminom")$recpro)[2])," events)")
ns=paste0("Non-seminoma", " (n=",length(subset(data_s, tumortype=="Nonseminom")$recpro[is.na(subset(data_s, tumortype=="Nonseminom")$recpro)==F]), ", ", as.numeric(table(subset(data_s, tumortype=="Nonseminom")$recpro)[2])," events)")

#' 
#' ## Print out tables
## -----------------------------------------------------------------------------
# save: Un-adjusted 
#Overall, Seminoma, Non-Seminoma
header=c("Model", rep(names(out_cox_1[, 2:4]), 3))
Cout_cox_1 <- rbind(c(" ", ov, " "," ", se, " "," ", ns, " "," " ), header,
                   cbind(out_cox_1, out_cox_S1[,2:4], out_cox_NS1[,2:4]), 
                   cbind(out_cox_2, out_cox_S2[,2:4], out_cox_NS2[,2:4]),
                   cbind(out_cox_2m, out_cox_S2m[,2:4], out_cox_NSm2[,2:4]),
                   cbind(out_cox_03m, out_cox_S03m[,2:4], out_cox_NSm03[,2:4]),
                   cbind(out_cox_3, out_cox_S3[,2:4], out_cox_NS3[,2:4]))
write.table(Cout_cox_1, file=paste0(dir_out, file2), col.names=F, row.names = F, quote=F, sep="\t")


## -----------------------------------------------------------------------------
# save: Cov. adjusted 
#Overall, Seminoma, Non-Seminoma
Cout_cox_1a <- rbind(c(" ", ov, " "," ", se, " "," ", ns, " "," " ), header,
                     cbind(out_cox_1a, out_cox_S1a[,2:4], out_cox_NS1a[,2:4]), 
                     cbind(out_cox_2a, out_cox_S2a[,2:4], out_cox_NS2a[,2:4]),
                     cbind(out_cox_2ma, out_cox_S2ma[,2:4], out_cox_NSm2a[,2:4]),
                     cbind(out_cox_3a, out_cox_S3a[,2:4], out_cox_NS3a[,2:4]))
write.table(Cout_cox_1a, file=paste0(dir_out, file2a), col.names=T, row.names = F, quote=F, sep="\t")

## -----------------------------------------------------------------------------
# save: Cov. adjusted, including vascular invasion
#Overall, Seminoma, Non-Seminoma
Cout_cox_1b <- rbind(c(" ", ov, " "," ", se, " "," ", ns, " "," " ), header,
                     cbind(out_cox_1b, out_cox_S1b[,2:4], out_cox_NS1b[,2:4]), 
                     cbind(out_cox_2b, out_cox_S2b[,2:4], out_cox_NS2b[,2:4]),
                     cbind(out_cox_2mb, out_cox_S2mb[,2:4], out_cox_NSm2b[,2:4]),
                     cbind(out_cox_3b, out_cox_S3b[,2:4], out_cox_NS3b[,2:4]))
write.table(Cout_cox_1b, file=paste0(dir_out, file2b), col.names=T, row.names = F, quote=F, sep="\t")
