#' ---
#' title: 'Association btw testis PRS (gwas) and risk of relapse in CS I tumor patients under SURVEILLANCE'
#' author: Emilio Ugalde
#' Date: 2026-05-04
#' ---
#' 
#' **DESCRIPTION** \
#' This scripts include: \
#' - Cox Regression analyses for association of PRS as continuous and categorical using both un-adjusted and adjusted models for:
#'     + **age at diagnosis and 3 PCs**. \
#'     + **age at diagnosis, vascular invasion, and 3 PCs**. \
#' 
#' 
## ----setup, include=FALSE, echo=F---------------------------------------------
suppressMessages(library("survival"))
suppressMessages(library("broom"))


#' Working directory
## ----echo=T-------------------------------------------------------------------
args <- commandArgs(trailingOnly = TRUE)
wd <- args[1]
if(is.na(wd)==T) wd=""

#' ## INPUT
# load dataset generated by "Format_Px_data_*.R" scripts
load(paste0(wd, './Data/patient_data.Rdat'))

#' 
#' Set OUTPUT
## ----echo=T-------------------------------------------------------------------
dir_out <- paste0(wd, "results/Tables/")
date_a <- format(Sys.Date(), "%Y%m%d")

#' 
#' - Results on relapse stage I under surveillance: 
#' For each covariate
## -----------------------------------------------------------------------------
file1 = paste0("Table_Covariates_relapse_CI_surveillance.", date_a, ".txt" )
#' 
#' - Results on relapse stage I under surveillance: 
#' PRS (un-adjusted, and adjusted models)
## -----------------------------------------------------------------------------
file2.0 = paste0("Table_nEvents_gwasPRS_relapse_CSI_surveillance.", date_a, ".txt" )
file2 = paste0("Table_gwasPRS_relapse_CI_surveillance.", date_a, ".txt" )
file2a = paste0("Table_gwasPRS_relapse_CI_surveillance_agedx_3PC_Adj.", date_a, ".txt" ) 
file2b = paste0("Table_gwasPRS_relapse_CI_surveillance_agedx_vasc_3PC_Adj.", date_a, ".txt" )
file3 = paste0("Table_ALLmodels.gwasPRS_relapse_CSI_surveillance.", date_a, ".txt" )

#' ## Summary functions
## -----------------------------------------------------------------------------
# Rounding
RD=2

#' 
## ----include=F----------------------------------------------------------------
# output summary function
sum_cox_out <- function(model, name) {
  out <- as.data.frame(tidy(model, exp=T, conf.int = T)[, c("term","estimate", "conf.low", "conf.high","p.value")])
  out$estimate <- round(out$estimate, RD)
  out$CI <- paste0(round(out$conf.low, RD), " to ", round(out$conf.high, RD))
  out <- out[, c("term","estimate", "CI","p.value")]
  colnames(out) <- c("Model","HR","95%CI","p.value")
  out$Model <- c(name)
  out[1,]
}
# for binary PRS
sum_cox_out2 <- function(model, name) {
  out <- as.data.frame(tidy(model, exp=T, conf.int = T)[, c("term","estimate", "conf.low", "conf.high","p.value")])
  out$estimate <- round(out$estimate, RD)
  out$CI <- paste0(round(out$conf.low, RD), " to ", round(out$conf.high, RD))
  out <- out[, c("term","estimate", "CI","p.value")]
  colnames(out) <- c("Model","HR","95%CI","p.value")
  out <- rbind(c("ref", "Ref.", "", ""), out)
  #out <- out[1,]
  levels <- as.character(unlist(model$xlevels[[1]]))
  out <- out[1:(length(levels)), ]
  out$Model <- paste0(name, " (",levels, ")")
  out
}
# for categorical PRS
# Assuming levels from first categorical variable (i.e. in this case, PRS tertiles)
sum_cox_out3 <- function(model, name) {
  out <- as.data.frame(tidy(model, exp=T, conf.int = T)[, c("term","estimate", "conf.low", "conf.high","p.value")])
  out$estimate <- round(out$estimate, RD)
  out$CI <- paste0(round(out$conf.low, RD), " to ", round(out$conf.high, RD))
  out <- out[, c("term","estimate", "CI","p.value")]
  colnames(out) <- c("Model","HR","95%CI","p.value")
  out <- rbind(c("ref", "Ref.", "", ""), out)
  levels <- as.character(unlist(model$xlevels[[1]]))
  #levels <- levels[2:length(levels)]
  out <- out[1:(length(levels)), ]
  out$Model <- paste0(name, " (",levels, ")")
  out
}

#' # Cox analysis: in stage I cases under surveillance
## ----echo=T-------------------------------------------------------------------

# Subset
if("rmh"%in%names(clin)) clin <- subset(clin, rmh=="CS I")
if("prim_beh"%in%names(clin)) clin <- subset(clin, prim_beh=="Surveillance")
data_s <- clin

# Drop missing levels: turmortype
data_s$tumortype <- droplevels(data_s$tumortype)

#' 
#' - Association of each covariate with relapse
## -----------------------------------------------------------------------------
cov_test <- c("agediag", "vasc_x", "tumortype", "PC1", "PC2", "PC3")
out_cov <- data.frame(covariate=cov_test, HR=rep(NA, length(cov_test)), coef=rep(NA, length(cov_test)), coef.se=rep(NA, length(cov_test)),
                      Z=rep(NA, length(cov_test)), P=rep(NA, length(cov_test)) )
for(C in cov_test){
    fm=formula(paste("Surv(timerec, recpro) ~", C, collapse = "") )
    res <- summary(coxph(fm, data=data_s))$coefficients
    out_cov[out_cov$covariate==C, ]$HR <- res[1,2]
    out_cov[out_cov$covariate==C, ]$coef <- res[1,1]
    out_cov[out_cov$covariate==C, ]$coef.se <- res[1,3]
    out_cov[out_cov$covariate==C, ]$Z <- res[1,4]
    out_cov[out_cov$covariate==C, ]$P <- res[1,5]
    rm(res)
}
out_cov$covariate <- c("Age diagnosis, yrs", "Vasc. infiltration (Yes vs. No)", "Hist (Non-seminoma Vs Seminoma)", "PC1", "PC2", "PC3")
# Save
write.table(out_cov, file=paste0(dir_out, file1), col.names=T, row.names = F, quote=F, sep="\t")

#' 
#' - Compile estimates per 1-SD 
#' - Compile estimates per 1-SD 
## -----------------------------------------------------------------------------
# Overall
out_cox_1 <- sum_cox_out(coxph(Surv(timerec, recpro)  ~ PRS_gwas_SDcases, data=data_s), "PRS (1-SD)")
out_cox_1a <- sum_cox_out(coxph(Surv(timerec, recpro)  ~ PRS_gwas_SDcases + agediag + PC1 + PC2 + PC3, data=data_s), "PRS (1-SD)")
out_cox_1b <- sum_cox_out(coxph(Surv(timerec, recpro)  ~ PRS_gwas_SDcases + agediag + vasc_x + PC1 + PC2 + PC3, data=data_s), "PRS (1-SD)")

# SEMINOMAS
out_cox_S1 <- sum_cox_out(coxph(Surv(timerec, recpro)  ~ PRS_gwas_SDcases, data=subset(data_s, tumortype=="Seminom")), "PRS (1-SD)" )
out_cox_S1a <- sum_cox_out(coxph(Surv(timerec, recpro)  ~ PRS_gwas_SDcases + agediag + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Seminom")), "PRS (1-SD)" )
out_cox_S1b <- sum_cox_out(coxph(Surv(timerec, recpro)  ~ PRS_gwas_SDcases + agediag + vasc_x + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Seminom")), "PRS (1-SD)" )

# NON-SEMINOMAS
out_cox_NS1 <- sum_cox_out(coxph(Surv(timerec, recpro)  ~ PRS_gwas_SDcases, data=subset(data_s, tumortype=="Nonseminom")), "PRS (1-SD)" )
out_cox_NS1a <- sum_cox_out(coxph(Surv(timerec, recpro)  ~ PRS_gwas_SDcases + agediag + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Nonseminom")), "PRS (1-SD)" )
out_cox_NS1b <- sum_cox_out(coxph(Surv(timerec, recpro)  ~ PRS_gwas_SDcases + agediag + vasc_x + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Nonseminom")), "PRS (1-SD)" )

#' 
#' - Compile estimates by mean distribution
## -----------------------------------------------------------------------------
# Overall
out_cox_2 <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_mean, data=data_s), "PRS")
out_cox_2a <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_mean + agediag + PC1 + PC2 + PC3, data=data_s), "PRS")
out_cox_2b <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_mean + agediag + vasc_x + PC1 + PC2 + PC3, data=data_s), "PRS")

# SEMINOMAS
out_cox_S2 <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_mean, data=subset(data_s, tumortype=="Seminom")), "PRS" )
out_cox_S2a <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_mean + agediag + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Seminom")), "PRS" )
out_cox_S2b <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_mean + agediag + vasc_x + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Seminom")), "PRS" )

# NON-SEMINOMAS
out_cox_NS2 <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_mean, data=subset(data_s, tumortype=="Nonseminom")), "PRS" )
out_cox_NS2a <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_mean + agediag + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Nonseminom")), "PRS" )
out_cox_NS2b <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_mean + agediag + vasc_x + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Nonseminom")), "PRS" )

#' 
#' - Compile estimates by MEDIAN distribution
## -----------------------------------------------------------------------------
# Overall
out_cox_2m <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_median, data=data_s), "PRS")
out_cox_2ma <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_median + agediag + PC1 + PC2 + PC3, data=data_s), "PRS")
out_cox_2mb <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_median + agediag + vasc_x + PC1 + PC2 + PC3, data=data_s), "PRS")

# SEMINOMAS
out_cox_S2m <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_median, data=subset(data_s, tumortype=="Seminom")), "PRS" )
out_cox_S2ma <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_median + agediag + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Seminom")), "PRS" )
out_cox_S2mb <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_median + agediag + vasc_x + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Seminom")), "PRS" )

# NON-SEMINOMAS
out_cox_NSm2 <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_median, data=subset(data_s, tumortype=="Nonseminom")), "PRS" )
out_cox_NSm2a <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_median + agediag + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Nonseminom")), "PRS" )
out_cox_NSm2b <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_median + agediag + vasc_x + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Nonseminom")), "PRS" )

#' 
#' - Compile estimates by TERTILE distribution
## -----------------------------------------------------------------------------
# Overall
out_cox_03m <- sum_cox_out3(coxph(Surv(timerec, recpro)  ~ PRS_gwas_tert_c, data=data_s), "PRS")
out_cox_03ma <- sum_cox_out3(coxph(Surv(timerec, recpro)  ~ PRS_gwas_tert_c + agediag + PC1 + PC2 + PC3, data=data_s), "PRS")
out_cox_03mb <- sum_cox_out3(coxph(Surv(timerec, recpro)  ~ PRS_gwas_tert_c + agediag + vasc_x + PC1 + PC2 + PC3, data=data_s), "PRS")

# SEMINOMAS
out_cox_S03m <- sum_cox_out3(coxph(Surv(timerec, recpro)  ~ PRS_gwas_tert_c, data=subset(data_s, tumortype=="Seminom")), "PRS" )
out_cox_S03ma <- sum_cox_out3(coxph(Surv(timerec, recpro)  ~ PRS_gwas_tert_c + agediag + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Seminom")), "PRS" )
out_cox_S03mb <- sum_cox_out3(coxph(Surv(timerec, recpro)  ~ PRS_gwas_tert_c + agediag + vasc_x + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Seminom")), "PRS" )

# NON-SEMINOMAS
out_cox_NSm03 <- sum_cox_out3(coxph(Surv(timerec, recpro)  ~ PRS_gwas_tert_c, data=subset(data_s, tumortype=="Nonseminom")), "PRS" )
out_cox_NSm03a <- sum_cox_out3(coxph(Surv(timerec, recpro)  ~ PRS_gwas_tert_c + agediag + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Nonseminom")), "PRS" )
out_cox_NSm03b <- sum_cox_out3(coxph(Surv(timerec, recpro)  ~ PRS_gwas_tert_c + agediag + vasc_x + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Nonseminom")), "PRS" )

#' 
#' - Compile estimates by high vs low tertile distribution
## -----------------------------------------------------------------------------
# Overall
out_cox_3 <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_th, data=data_s), "PRS")
out_cox_3a <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_th + agediag + PC1 + PC2 + PC3, data=data_s), "PRS")
out_cox_3b <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_th + agediag + vasc_x + PC1 + PC2 + PC3, data=data_s), "PRS*")

# SEMINOMAS
out_cox_S3 <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_th, data=subset(data_s, tumortype=="Seminom")), "PRS" )
out_cox_S3a <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_th + agediag + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Seminom")), "PRS" )
out_cox_S3b <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_th + agediag + vasc_x + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Seminom")), "PRS*" )

# NON-SEMINOMAS
out_cox_NS3 <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_th, data=subset(data_s, tumortype=="Nonseminom")), "PRS" )
out_cox_NS3a <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_th + agediag + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Nonseminom")), "PRS" )
out_cox_NS3b <- sum_cox_out2(coxph(Surv(timerec, recpro)  ~ PRS_gwas_th + agediag + vasc_x + PC1 + PC2 + PC3, data=subset(data_s, tumortype=="Nonseminom")), "PRS*" )


#' ## Print out tables
## -----------------------------------------------------------------------------

#' - Sample size and events per PRS strata

dO=subset(data_s, is.na(recpro)==F)
dS=subset(dO, tumortype=="Seminom")
dN=subset(dO, tumortype=="Nonseminom")

nev_c_O=data.frame(n=length(dO$recpro[is.na(dO$recpro)==F]), n_events=as.numeric(table(dO$recpro)[2]))
nev_c_S=data.frame(n=length(dS$recpro[is.na(dS$recpro)==F]), n_events=as.numeric(table(dS$recpro)[2]))
nev_c_N=data.frame(n=length(dN$recpro[is.na(dN$recpro)==F]), n_events=as.numeric(table(dN$recpro)[2]))

nev_O_mean=data.frame(n=as.numeric(table(dO$PRS_gwas_mean)), n_events=table(dO$PRS_gwas_mean, dO$recpro)[,2])
nev_S_mean=data.frame(n=as.numeric(table(dS$PRS_gwas_mean)), n_events=table(dS$PRS_gwas_mean, dS$recpro)[,2])
nev_N_mean=data.frame(n=as.numeric(table(dN$PRS_gwas_mean)), n_events=table(dN$PRS_gwas_mean, dN$recpro)[,2])

nev_O_median=data.frame(n=as.numeric(table(dO$PRS_gwas_median)), n_events=table(dO$PRS_gwas_median, dO$recpro)[,2])
nev_S_median=data.frame(n=as.numeric(table(dS$PRS_gwas_median)), n_events=table(dS$PRS_gwas_median, dS$recpro)[,2])
nev_N_median=data.frame(n=as.numeric(table(dN$PRS_gwas_median)), n_events=table(dN$PRS_gwas_median, dN$recpro)[,2])

nev_O_tert=data.frame(n=as.numeric(table(dO$PRS_gwas_tert_c)), n_events=table(dO$PRS_gwas_tert_c, dO$recpro)[,2])
nev_S_tert=data.frame(n=as.numeric(table(dS$PRS_gwas_tert_c)), n_events=table(dS$PRS_gwas_tert_c, dS$recpro)[,2])
nev_N_tert=data.frame(n=as.numeric(table(dN$PRS_gwas_tert_c)), n_events=table(dN$PRS_gwas_tert_c, dN$recpro)[,2])

nev_O_th=data.frame(n=as.numeric(table(dO$PRS_gwas_th)), n_events=table(dO$PRS_gwas_th, dO$recpro)[,2])
nev_S_th=data.frame(n=as.numeric(table(dS$PRS_gwas_th)), n_events=table(dS$PRS_gwas_th, dS$recpro)[,2])
nev_N_th=data.frame(n=as.numeric(table(dN$PRS_gwas_th)), n_events=table(dN$PRS_gwas_th, dN$recpro)[,2])

out_nevents=rbind(cbind(nev_c_O, nev_c_S, nev_c_N),
                  cbind(nev_O_mean, nev_S_mean, nev_N_mean),
                  cbind(nev_O_median, nev_S_median, nev_N_median),
                  cbind(nev_O_tert, nev_S_tert, nev_N_tert),
                  cbind(nev_O_th[2,], nev_S_th[2,], nev_N_th[2,])
)
row.names(out_nevents)[1] <- c("Continuous")
out_nevents$PRS <- row.names(out_nevents)
header <- c("", "Overall","","Seminoma","","Non-seminoma","")
sub_header <- c("PRS", names(out_nevents)[!names(out_nevents)%in%"PRS"])
out_nevents <- out_nevents[, c(7,1:6)]
cat(paste0(paste(header, collapse = "\t"), "\n"), file=paste0(dir_out, file2.0))
cat(paste0(paste(sub_header, collapse = "\t"), "\n"), file=paste0(dir_out, file2.0), append = T)
write.table(out_nevents, file=paste0(dir_out, file2.0), col.names=F, row.names = F, quote=F, sep="\t", append = T)

## Print Cox-PRS results
## -----------------------------------------------------------------------------

## To layout: models (sub-rows)/ histology (sub-columns)
## - Prepare table header (n, nevents)
header=c(" ", "Overall"," "," "," ", " ", "Seminoma"," "," "," ", " ", "Non-seminoma"," "," ", " "," " )
sub_header=c(" ", rep(c(c("n", "n events") , names(out_cox_1[, 2:4])), 3))


# save: Un-adjusted 
#Overall, Seminoma, Non-Seminoma
name_model=c("Un-adjusted analysis", " "," "," "," ", " ", " "," "," "," ", " ", " "," "," ", " "," " )
Cout_cox_1 <- rbind(cbind(nev_c_O, out_cox_1, nev_c_S, out_cox_S1[,2:4], nev_c_N, out_cox_NS1[,2:4]),
                    cbind(nev_O_mean, out_cox_2, nev_S_mean, out_cox_S2[,2:4], nev_N_mean, out_cox_NS2[,2:4]),
                    cbind(nev_O_median, out_cox_2m, nev_S_median, out_cox_S2m[,2:4], nev_N_median, out_cox_NSm2[,2:4]),
                    cbind(nev_O_tert, out_cox_03m, nev_S_tert, out_cox_S03m[,2:4], nev_N_tert, out_cox_NSm03[,2:4]),
                    cbind(nev_O_th, out_cox_3, nev_S_th, out_cox_S3[,2:4], nev_N_th, out_cox_NS3[,2:4]))
# order header and remove duplicated ref. row for 1st tertile on last strata 
Cout_cox_1 <- Cout_cox_1[-c(nrow(Cout_cox_1)-1), c(3,1,2,4:length(header))]

cat(paste0(paste(header, collapse = "\t"), "\n"), file=paste0(dir_out, file2))
cat(paste0(paste(sub_header, collapse = "\t"), "\n"), file=paste0(dir_out, file2), append = T)
cat(paste0(paste(name_model, collapse = "\t"), "\n"), file=paste0(dir_out, file2), append = T)
write.table(Cout_cox_1, file=paste0(dir_out, file2), col.names=F, row.names = F, quote=F, sep="\t", append = T)

# save: Cov. adjusted 
#Overall, Seminoma, Non-Seminoma
name_model=c("Adjusted for age at diagnosis and 3 PCs", " "," "," "," ", " ", " "," "," "," ", " ", " "," "," ", " "," " )
Cout_cox_1a <- rbind(cbind(nev_c_O, out_cox_1a, nev_c_S, out_cox_S1a[,2:4], nev_c_N, out_cox_NS1a[,2:4]),
                     cbind(nev_O_mean, out_cox_2a, nev_S_mean, out_cox_S2a[,2:4], nev_N_mean, out_cox_NS2a[,2:4]),
                     cbind(nev_O_median, out_cox_2ma, nev_S_median, out_cox_S2ma[,2:4], nev_N_median, out_cox_NSm2a[,2:4]),
                     cbind(nev_O_tert, out_cox_03ma, nev_S_tert, out_cox_S03ma[,2:4], nev_N_tert, out_cox_NSm03a[,2:4]),
                     cbind(nev_O_th, out_cox_3a, nev_S_th, out_cox_S3a[,2:4], nev_N_th, out_cox_NS3a[,2:4]))
# order header and remove duplicated ref. row for 1st tertile on last strata 
Cout_cox_1a <- Cout_cox_1a[-c(nrow(Cout_cox_1a)-1), c(3,1,2,4:length(header))]

cat(paste0(paste(header, collapse = "\t"), "\n"), file=paste0(dir_out, file2a))
cat(paste0(paste(sub_header, collapse = "\t"), "\n"), file=paste0(dir_out, file2a), append = T)
cat(paste0(paste(name_model, collapse = "\t"), "\n"), file=paste0(dir_out, file2a), append = T)
write.table(Cout_cox_1a, file=paste0(dir_out, file2a), col.names=F, row.names = F, quote=F, sep="\t", append = T)

# save: Cov. adjusted, including vascular invasion
# Overall, Seminoma, Non-Seminoma
name_model=c("Adjusted for age at diagnosis, 3 PCs and vascular infiltration", " "," "," "," ", " ", " "," "," "," ", " ", " "," "," ", " "," " )
Cout_cox_1b <- rbind(cbind(nev_c_O, out_cox_1b, nev_c_S, out_cox_S1b[,2:4], nev_c_N, out_cox_NS1b[,2:4]),
                     cbind(nev_O_mean, out_cox_2b, nev_S_mean, out_cox_S2b[,2:4], nev_N_mean, out_cox_NS2b[,2:4]),
                     cbind(nev_O_median, out_cox_2mb, nev_S_median, out_cox_S2mb[,2:4], nev_N_median, out_cox_NSm2b[,2:4]),
                     cbind(nev_O_tert, out_cox_03mb, nev_S_tert, out_cox_S03mb[,2:4], nev_N_tert, out_cox_NSm03b[,2:4]),
                     cbind(nev_O_th, out_cox_3b, nev_S_th, out_cox_S3b[,2:4], nev_N_th, out_cox_NS3b[,2:4]))  

cat(paste0(paste(header, collapse = "\t"), "\n"), file=paste0(dir_out, file2b))
cat(paste0(paste(sub_header, collapse = "\t"), "\n"), file=paste0(dir_out, file2b), append = T)
cat(paste0(paste(name_model, collapse = "\t"), "\n"), file=paste0(dir_out, file2b), append = T)
write.table(Cout_cox_1b, file=paste0(dir_out, file2b), col.names=F, row.names = F, quote=F, sep="\t", append = T)

## -----------------------------------------------------------------------------
## All results in one table
## -----------------------------------------------------------------------------
## To layout: histoloy (sub-rows) / models (sub-columns)
## NOTE: order columns and remove duplicated ref. row for 1st tertile on last strata, on each hist. group 

header_v2=c(" "," ", " ", "Un-adjusted"," "," ","Cov.adj.(ageDx+3PCs)"," ", " ", "Cov.adj.(ageDx+3PCs+VI)"," "," ") 
sub_header_v2=c("PRS", "n", "n events",  rep(names(out_cox_1[, 2:4]),3) ) 

c_res_O <- rbind(c(" "," ", "Overall", " "," "," "," "," ", " ", " "," "," "),
                 cbind(nev_c_O, out_cox_1, out_cox_1a[,2:4], out_cox_1b[,2:4]), # cont.
                 cbind(nev_O_mean, out_cox_2, out_cox_2a[,2:4], out_cox_2b[,2:4]), # mean
                 cbind(nev_O_median, out_cox_2m, out_cox_2ma[,2:4], out_cox_2mb[,2:4]), # median
                 cbind(nev_O_tert, out_cox_03m, out_cox_03ma[,2:4], out_cox_03mb[,2:4]), # tertiles
                 cbind(nev_O_th, out_cox_3, out_cox_3a[,2:4], out_cox_3b[,2:4])) # low Vs higher tertiles
c_res_O <- c_res_O[-c(nrow(c_res_O)-1), c(3,1,2,4:length(header_v2))]

c_res_S <- rbind(c(" "," ", "Seminoma", " "," "," "," "," ", " ", " "," "," "),
                 cbind(nev_c_S, out_cox_S1, out_cox_S1a[,2:4], out_cox_S1b[,2:4]),
                 cbind(nev_S_mean, out_cox_S2, out_cox_S2a[,2:4], out_cox_S2b[,2:4]),
                 cbind(nev_S_median, out_cox_S2m, out_cox_S2ma[,2:4], out_cox_S2mb[,2:4]),
                 cbind(nev_S_tert, out_cox_S03m, out_cox_S03ma[,2:4], out_cox_S03mb[,2:4]),
                 cbind(nev_S_th, out_cox_S3, out_cox_S3a[,2:4], out_cox_S3b[,2:4]))
c_res_S <- c_res_S[-c(nrow(c_res_S)-1), c(3,1,2,4:length(header_v2))]

c_res_NS <- rbind(c(" "," ", "Non-seminoma", " "," "," "," "," ", " ", " "," "," "),
                  cbind(nev_c_N, out_cox_NS1, out_cox_NS1a[,2:4], out_cox_NS1b[,2:4]),
                  cbind(nev_N_mean, out_cox_NS2, out_cox_NS2a[,2:4], out_cox_NS2b[,2:4]),                  
                  cbind(nev_N_median, out_cox_NSm2, out_cox_NSm2a[,2:4], out_cox_NSm2b[,2:4]),
                  cbind(nev_S_tert, out_cox_NSm03, out_cox_NSm03a[,2:4], out_cox_NSm03b[,2:4]),
                  cbind(nev_N_th, out_cox_NS3, out_cox_NS3a[,2:4], out_cox_NS3b[,2:4]) )
c_res_NS <- c_res_NS[-c(nrow(c_res_NS)-1), c(3,1,2,4:length(header_v2))]

c_res_out <- rbind(c_res_O, c_res_S, c_res_NS)

cat(paste0(paste(header_v2, collapse = "\t"), "\n"), file=paste0(dir_out, file3))
cat(paste0(paste(sub_header_v2, collapse = "\t"), "\n"), file=paste0(dir_out, file3), append = T)
write.table(c_res_out, file=paste0(dir_out, file3), col.names=F, row.names = F, quote=F, sep="\t", append = T)
